import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/util/Navbar";
import { CartProvider } from "@/context/CartContext";
import { Toast } from "radix-ui";
import { Toaster } from "sonner";
import { TableProvider } from "@/context/tableContext";
// import { TableProvider } from "@/context/tableContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<TableProvider>
<CartProvider>
  
        <Navbar/>
        {children}
          <Toaster position="top-right" richColors />

</CartProvider>
</TableProvider>
      </body>
    </html>
  );
}
